language: node_js
node_js:
- '4'
- '5'
- '6'
before_script:
- rm -rf ./coverage
after_script:
- test -e ./coverage/lcov.info && < ./coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js
env:
  global:
    service_name: travis-ci	
notifications:
  slack: sockdrawer:6bn0VFi2HhWot4A7bwO5FVW5